from __future__ import annotations


LANGUAGE_GROUPS = {
    "English":      ["en"],
    "LatinCore":    ["es", "fr", "de", "it", "pt", "nl"],
    "LatinTier2":   ["vi", "tr", "la", "id", "ms", "af", "sq", "is", "no", "sv", "da", "fi", "hu", "pl", "cs", "ro"],
    "Cyrillic":     ["ru", "bg", "uk", "sr", "be", "kk", "mk", "mn"],
    "EastAsian":    ["zh", "ja", "ko"],
    "Indic":        ["hi", "ur", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "as", "or"],
    "ArabicScript": ["ar", "fa", "ps", "sd", "ug"],
    "OtherScripts": ["el", "he", "hy", "ka", "am", "km", "lo", "my", "th"],
}

LANG_ISO2_TO_ISO3 = {
    "en": "eng",
    "es": "spa",
    "fr": "fra",
    "de": "deu",
    "it": "ita",
    "pt": "por",
    "nl": "nld",
    "vi": "vie",
    "tr": "tur",
    "la": "lat",
    "id": "ind",
    "ms": "msa",
    "af": "afr",
    "sq": "sqi",
    "is": "isl",
    "no": "nor",
    "sv": "swe",
    "da": "dan",
    "fi": "fin",
    "hu": "hun",
    "pl": "pol",
    "cs": "ces",
    "ro": "ron",
    "ru": "rus",
    "bg": "bul",
    "uk": "ukr",
    "sr": "srp",
    "be": "bel",
    "kk": "kaz",
    "mk": "mkd",
    "mn": "mon",
    "zh": "zho",
    "ja": "jpn",
    "ko": "kor",
    "hi": "hin",
    "ur": "urd",
    "bn": "ben",
    "ta": "tam",
    "te": "tel",
    "mr": "mar",
    "gu": "guj",
    "kn": "kan",
    "ml": "mal",
    "pa": "pan",
    "as": "asm",
    "or": "ori",
    "ar": "ara",
    "fa": "fas",
    "ps": "pus",
    "sd": "snd",
    "ug": "uig",
    "el": "ell",
    "he": "heb",
    "hy": "hye",
    "ka": "kat",
    "am": "amh",
    "km": "khm",
    "lo": "lao",
    "my": "mya",
    "th": "tha",
}
ALL_LANGS = [lang for langs in LANGUAGE_GROUPS.values() for lang in langs]
LANG_TO_GROUP = {lang: group for group, langs in LANGUAGE_GROUPS.items() for lang in langs}
