from __future__ import annotations

RESERVE_FRACTION = 0.15
MIN_RESERVED_SENTENCES = 4
MAX_RESERVED_SENTENCES = 20_000
SMOL_RESERVE_FRACTION = 0.50
SMOL_MIN_RESERVED_SENTENCES = 1
SMOL_MAX_RESERVED_SENTENCES = MAX_RESERVED_SENTENCES
FT_RESERVE_FRACTION = 0.10
FT_MIN_RESERVED_SENTENCES = 1
FT_MAX_RESERVED_SENTENCES = MAX_RESERVED_SENTENCES
FT_MAX_SENTENCES_PER_LANG = 5_000
FT_INCLUDE_TRANSLATED_ENGLISH = False
USE_SMOL_AUGMENTATION = True
USE_FINETRANS_AUGMENTATION = True
SMOL_FORCE_REBUILD = False
FT_FORCE_REBUILD = False
