from __future__ import annotations


RESERVE_FRACTION = 0.15
MIN_RESERVED_SENTENCES = 4
MAX_RESERVED_SENTENCES = 20_000
SMOL_RESERVE_FRACTION = 0.50
SMOL_MIN_RESERVED_SENTENCES = 1
SMOL_MAX_RESERVED_SENTENCES = MAX_RESERVED_SENTENCES
